//
// Generated file, do not edit! Created by nedtool 5.2 from src/KOPSMsg.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __KOPSMSG_M_H
#define __KOPSMSG_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0502
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>src/KOPSMsg.msg:16</tt> by nedtool.
 * <pre>
 * packet KDataMsg
 * {
 *     // common fields
 *     string sourceAddress;
 *     string destinationAddress;
 *     string dataName;
 *     string dummyPayloadContent;
 *     int msgType;
 *     double validUntilTime = 0;
 *     int msgUniqueID;
 * 
 *     int realPayloadSize;
 *     int realPacketSize;
 * 
 *     int hopsTravelled = 0;
 * 
 *     // destination oriented delivery specific fields
 *     string originatorNodeName;
 *     string finalDestinationNodeName;
 *     string finalDestinationNodeAddress;
 *     bool destinationOriented = false;
 * 
 *     // keetchi specific fields
 *     int goodnessValue = 50;
 * 
 *     // epidemic routing specific fields
 *     string messageID;
 *     int hopCount = 255;
 * }
 * 
 * //
 * // Format of a Feedback packet.
 * //
 * // \@author : Asanga Udugama (adu\@comnets.uni-bremen.de)
 * // \@date   : 06-oct-2015
 * //
 * //
 * // example sizes in bytes
 * //
 * //               addrs | data name | goodness value | total  |
 * //               s & d | or msg ID |  (1 byte int)  | (bytes)|
 * // Keetchi  ->   6 + 6     64             1             77
 * //
 * </pre>
 */
class KDataMsg : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string sourceAddress;
    ::omnetpp::opp_string destinationAddress;
    ::omnetpp::opp_string dataName;
    ::omnetpp::opp_string dummyPayloadContent;
    int msgType;
    double validUntilTime;
    int msgUniqueID;
    int realPayloadSize;
    int realPacketSize;
    int hopsTravelled;
    ::omnetpp::opp_string originatorNodeName;
    ::omnetpp::opp_string finalDestinationNodeName;
    ::omnetpp::opp_string finalDestinationNodeAddress;
    bool destinationOriented;
    int goodnessValue;
    ::omnetpp::opp_string messageID;
    int hopCount;

  private:
    void copy(const KDataMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const KDataMsg&);

  public:
    KDataMsg(const char *name=nullptr, short kind=0);
    KDataMsg(const KDataMsg& other);
    virtual ~KDataMsg();
    KDataMsg& operator=(const KDataMsg& other);
    virtual KDataMsg *dup() const override {return new KDataMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getSourceAddress() const;
    virtual void setSourceAddress(const char * sourceAddress);
    virtual const char * getDestinationAddress() const;
    virtual void setDestinationAddress(const char * destinationAddress);
    virtual const char * getDataName() const;
    virtual void setDataName(const char * dataName);
    virtual const char * getDummyPayloadContent() const;
    virtual void setDummyPayloadContent(const char * dummyPayloadContent);
    virtual int getMsgType() const;
    virtual void setMsgType(int msgType);
    virtual double getValidUntilTime() const;
    virtual void setValidUntilTime(double validUntilTime);
    virtual int getMsgUniqueID() const;
    virtual void setMsgUniqueID(int msgUniqueID);
    virtual int getRealPayloadSize() const;
    virtual void setRealPayloadSize(int realPayloadSize);
    virtual int getRealPacketSize() const;
    virtual void setRealPacketSize(int realPacketSize);
    virtual int getHopsTravelled() const;
    virtual void setHopsTravelled(int hopsTravelled);
    virtual const char * getOriginatorNodeName() const;
    virtual void setOriginatorNodeName(const char * originatorNodeName);
    virtual const char * getFinalDestinationNodeName() const;
    virtual void setFinalDestinationNodeName(const char * finalDestinationNodeName);
    virtual const char * getFinalDestinationNodeAddress() const;
    virtual void setFinalDestinationNodeAddress(const char * finalDestinationNodeAddress);
    virtual bool getDestinationOriented() const;
    virtual void setDestinationOriented(bool destinationOriented);
    virtual int getGoodnessValue() const;
    virtual void setGoodnessValue(int goodnessValue);
    virtual const char * getMessageID() const;
    virtual void setMessageID(const char * messageID);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const KDataMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, KDataMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>src/KOPSMsg.msg:60</tt> by nedtool.
 * <pre>
 * packet KFeedbackMsg
 * {
 *     // common fields
 *     string sourceAddress;
 *     string destinationAddress;
 *     string dataName;
 * 
 *     int realPacketSize;
 * 
 *     // keetchi specific fields
 *     int goodnessValue;
 *     int feedbackType;
 * }
 * 
 * //
 * // Summary vector exchange message (used with Epidemic Routing).
 * //
 * // \@author : Asanga Udugama (adu\@comnets.uni-bremen.de)
 * // \@date   : 02-may-2017
 * //
 * //
 * // example sizes in bytes
 * //
 * //                addrs | msg ID hashes  | total  |
 * //                s & d | 2 bytes x count| (bytes)|
 * // Epidemic  ->   6 + 6     2 x 10           32
 * </pre>
 */
class KFeedbackMsg : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string sourceAddress;
    ::omnetpp::opp_string destinationAddress;
    ::omnetpp::opp_string dataName;
    int realPacketSize;
    int goodnessValue;
    int feedbackType;

  private:
    void copy(const KFeedbackMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const KFeedbackMsg&);

  public:
    KFeedbackMsg(const char *name=nullptr, short kind=0);
    KFeedbackMsg(const KFeedbackMsg& other);
    virtual ~KFeedbackMsg();
    KFeedbackMsg& operator=(const KFeedbackMsg& other);
    virtual KFeedbackMsg *dup() const override {return new KFeedbackMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getSourceAddress() const;
    virtual void setSourceAddress(const char * sourceAddress);
    virtual const char * getDestinationAddress() const;
    virtual void setDestinationAddress(const char * destinationAddress);
    virtual const char * getDataName() const;
    virtual void setDataName(const char * dataName);
    virtual int getRealPacketSize() const;
    virtual void setRealPacketSize(int realPacketSize);
    virtual int getGoodnessValue() const;
    virtual void setGoodnessValue(int goodnessValue);
    virtual int getFeedbackType() const;
    virtual void setFeedbackType(int feedbackType);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const KFeedbackMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, KFeedbackMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>src/KOPSMsg.msg:87</tt> by nedtool.
 * <pre>
 * packet KSummaryVectorMsg
 * {
 *     // common fields
 *     string sourceAddress;
 *     string destinationAddress;
 * 
 *     int realPacketSize;
 * 
 *     // epidemic routing specific fields
 *     string messageIDHashVector[];  // summary vector
 * }
 * 
 * //
 * // Data request message (used with Epidemic Routing).
 * //
 * // \@author : Asanga Udugama (adu\@comnets.uni-bremen.de)
 * // \@date   : 02-may-2017
 * //
 * //
 * // example sizes in bytes
 * //
 * //                addrs | msg ID hashes  | total  |
 * //                s & d | 2 bytes x count| (bytes)|
 * // Epidemic  ->   6 + 6     2 x 5            32
 * </pre>
 */
class KSummaryVectorMsg : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string sourceAddress;
    ::omnetpp::opp_string destinationAddress;
    int realPacketSize;
    ::omnetpp::opp_string *messageIDHashVector; // array ptr
    unsigned int messageIDHashVector_arraysize;

  private:
    void copy(const KSummaryVectorMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const KSummaryVectorMsg&);

  public:
    KSummaryVectorMsg(const char *name=nullptr, short kind=0);
    KSummaryVectorMsg(const KSummaryVectorMsg& other);
    virtual ~KSummaryVectorMsg();
    KSummaryVectorMsg& operator=(const KSummaryVectorMsg& other);
    virtual KSummaryVectorMsg *dup() const override {return new KSummaryVectorMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getSourceAddress() const;
    virtual void setSourceAddress(const char * sourceAddress);
    virtual const char * getDestinationAddress() const;
    virtual void setDestinationAddress(const char * destinationAddress);
    virtual int getRealPacketSize() const;
    virtual void setRealPacketSize(int realPacketSize);
    virtual void setMessageIDHashVectorArraySize(unsigned int size);
    virtual unsigned int getMessageIDHashVectorArraySize() const;
    virtual const char * getMessageIDHashVector(unsigned int k) const;
    virtual void setMessageIDHashVector(unsigned int k, const char * messageIDHashVector);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const KSummaryVectorMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, KSummaryVectorMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>src/KOPSMsg.msg:112</tt> by nedtool.
 * <pre>
 * packet KDataRequestMsg
 * {
 *     // common fields
 *     string sourceAddress;
 *     string destinationAddress;
 * 
 *     int realPacketSize;
 * 
 *     // epidemic routing specific fields
 *     string messageIDHashVector[];  // request vector
 * }
 * 
 * 
 * //
 * // DP table request message (used with Prophet Routing).
 * //
 * //
 * //
 * //
 * //
 * // example sizes in bytes
 * //
 * //                addrs |  total  |
 * //                s & d | (bytes) |
 * // Prophet  ->    6 + 6      12
 * </pre>
 */
class KDataRequestMsg : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string sourceAddress;
    ::omnetpp::opp_string destinationAddress;
    int realPacketSize;
    ::omnetpp::opp_string *messageIDHashVector; // array ptr
    unsigned int messageIDHashVector_arraysize;

  private:
    void copy(const KDataRequestMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const KDataRequestMsg&);

  public:
    KDataRequestMsg(const char *name=nullptr, short kind=0);
    KDataRequestMsg(const KDataRequestMsg& other);
    virtual ~KDataRequestMsg();
    KDataRequestMsg& operator=(const KDataRequestMsg& other);
    virtual KDataRequestMsg *dup() const override {return new KDataRequestMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getSourceAddress() const;
    virtual void setSourceAddress(const char * sourceAddress);
    virtual const char * getDestinationAddress() const;
    virtual void setDestinationAddress(const char * destinationAddress);
    virtual int getRealPacketSize() const;
    virtual void setRealPacketSize(int realPacketSize);
    virtual void setMessageIDHashVectorArraySize(unsigned int size);
    virtual unsigned int getMessageIDHashVectorArraySize() const;
    virtual const char * getMessageIDHashVector(unsigned int k) const;
    virtual void setMessageIDHashVector(unsigned int k, const char * messageIDHashVector);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const KDataRequestMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, KDataRequestMsg& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>src/KOPSMsg.msg:139</tt> by nedtool.
 * <pre>
 * packet DPtableRequestMsg
 * {
 *     // common fields
 *     string sourceAddress;
 *     string destinationAddress;
 * }
 * 
 * 
 * //
 * // Dp table message (used with Prophet Routing).
 * //
 * //
 * //
 * //
 * // example sizes in bytes
 * //
 * //                addrs | dplist         | total  |
 * //                s & d | 14 bytes x count| (bytes)|
 * // Prophet  ->   6 + 6     (6+6+2)           26
 * </pre>
 */
class DPtableRequestMsg : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string sourceAddress;
    ::omnetpp::opp_string destinationAddress;

  private:
    void copy(const DPtableRequestMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DPtableRequestMsg&);

  public:
    DPtableRequestMsg(const char *name=nullptr, short kind=0);
    DPtableRequestMsg(const DPtableRequestMsg& other);
    virtual ~DPtableRequestMsg();
    DPtableRequestMsg& operator=(const DPtableRequestMsg& other);
    virtual DPtableRequestMsg *dup() const override {return new DPtableRequestMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getSourceAddress() const;
    virtual void setSourceAddress(const char * sourceAddress);
    virtual const char * getDestinationAddress() const;
    virtual void setDestinationAddress(const char * destinationAddress);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DPtableRequestMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DPtableRequestMsg& obj) {obj.parsimUnpack(b);}

/**
 * Struct generated from src/KOPSMsg.msg:159 by nedtool.
 */
struct delivPredictability
{
    delivPredictability();
    ::omnetpp::opp_string nodeMACAddress;
    double nodeDP;
};

// helpers for local use
void __doPacking(omnetpp::cCommBuffer *b, const delivPredictability& a);
void __doUnpacking(omnetpp::cCommBuffer *b, delivPredictability& a);

inline void doParsimPacking(omnetpp::cCommBuffer *b, const delivPredictability& obj) { __doPacking(b, obj); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, delivPredictability& obj) { __doUnpacking(b, obj); }

/**
 * Class generated from <tt>src/KOPSMsg.msg:165</tt> by nedtool.
 * <pre>
 * packet DPtableDataMsg
 * {
 *     // common fields
 *     string sourceAddress;
 *     string destinationAddress;
 *     delivPredictability dpList[];
 * 
 * }
 * </pre>
 */
class DPtableDataMsg : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string sourceAddress;
    ::omnetpp::opp_string destinationAddress;
    delivPredictability *dpList; // array ptr
    unsigned int dpList_arraysize;

  private:
    void copy(const DPtableDataMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DPtableDataMsg&);

  public:
    DPtableDataMsg(const char *name=nullptr, short kind=0);
    DPtableDataMsg(const DPtableDataMsg& other);
    virtual ~DPtableDataMsg();
    DPtableDataMsg& operator=(const DPtableDataMsg& other);
    virtual DPtableDataMsg *dup() const override {return new DPtableDataMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getSourceAddress() const;
    virtual void setSourceAddress(const char * sourceAddress);
    virtual const char * getDestinationAddress() const;
    virtual void setDestinationAddress(const char * destinationAddress);
    virtual void setDpListArraySize(unsigned int size);
    virtual unsigned int getDpListArraySize() const;
    virtual delivPredictability& getDpList(unsigned int k);
    virtual const delivPredictability& getDpList(unsigned int k) const {return const_cast<DPtableDataMsg*>(this)->getDpList(k);}
    virtual void setDpList(unsigned int k, const delivPredictability& dpList);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DPtableDataMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DPtableDataMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __KOPSMSG_M_H

